name: dinox_env
channels:
  - conda-forge
dependencies:
  - jax=0.4.25=pyhd8ed1ab_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - optax=0.2.1=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - poetry=1.8.2=linux_pyha804496_0
  - poetry-core=1.9.0=pyhd8ed1ab_0
  - poetry-plugin-export=1.7.1=pyhd8ed1ab_0
  - python=3.10.14=hd12c33a_0_cpython
  - pip:
      - equinox==0.11.3
