[tool.poetry]
name = "dinox"
version = "0.1.0"
description = "Derivative Informed Neural Operators in JAX"
authors = [
    "Joshua Chen <joshuawchen@icloud.com>",
    "Tom O'Leary Roseberry <tom.olearyroseberry@utexas.edu>"
]
license = "GNU Lesser General Public License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
equinox = "^0.11.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"